version: '3.2'
services:
  myjenkins:
    build: .
    command:
      - --rm
    ports:
      - "8080:8080"
    volumes:
      - /var/jenkins_home/casc.yaml
      - /home/sumit/jenkinsdata:/var/jenkins_home
    environment:
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: password


